# Name of your blog
name: Praveen's blog

# Short description
description: This is my blog that is built by generating json files from markdown

# Your name
author: Praveen Kumar

# Your email 
author_email: mail@pkp.io

# The directory for category index pages
category_dir: category/

# The relative URL to access blog resources (to refer to assests).
url: /blog/jekyll 


#### Under the Hood Stuff #####
# Markdown settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", 
		"with_toc_data", "fenced_code_blocks", "superscript", "underline", 
		"highlight"]

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
# Unfortunately .json exention is not supported by jekyll :(
permalink: /:title/

# How many articles do you wish to appear on the front page:
#paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [package.json, node_modules, app.yaml]

